### ISSUE TITLE
error when trying to list rss..

### ISSUE THREAD

**Issue by misu200** [jra11/google-alerts-export-import#1]
I ve configured the username/pass for the google account and tryng to test the tool

alerts-export-import]# casperjs galerts.js listrss                                                           CasperError: Cannot get information from xpath selector: //*/div[@class="alert_buttons"]/a: no elements found.
  /root/mihai_others/n1k0-casperjs-4f105a9/modules/casper.js:1073 in getElementsInfo                                                /root/google-alerts-export-import/galerts.js:194
  /root/mihai_others/n1k0-casperjs-4f105a9/modules/casper.js:1553 in runStep
  /root/mihai_others/n1k0-casperjs-4f105a9/modules/casper.js:399 in checkStep

**Comment by misu200** [comment]
everything worked for me by adding extra parameters (SSL problem):

casperjs --ssl-protocol=tlsv1   --ignore-ssl-errors=yes galerts.js listrss

I am using casperjs 1.1.0-beta3 and phantomjs 1.9.8

**Comment by jra11** [comment]
Added in the doc.
