### ISSUE TITLE
can't set the "Language" value for a google alert

### ISSUE THREAD

**Issue by misu200** [jra11/google-alerts-export-import#2]
I have the following setting in my file for insert:
"AUTOMOBILE-DACIA SA";At most once a day;auto;Polish;any;best;rss

For some unknown reason the only languages i can configure for an alert are the first ones that gets first   displayed in the dropdown menu ( e.g English or Arabic )... but not the ones that are more down in the list ..like Polish.

I ve activated debug and there are no errors reported:
[debug] [phantom] Changing Dropdown 3 of alert to Polish
[debug] [phantom] Mouse event 'mousedown' on selector: xpath selector: (//_/div[@class="goog-inline-block goog-flat-menu-button-caption"])[3]
[debug] [phantom] Mouse event 'mouseup' on selector: xpath selector: (//_/div[@class="goog-inline-block goog-flat-menu-button-caption"])[3]
[debug] [phantom] Mouse event 'click' on selector: xpath selector: (//*/div[@class="goog-inline-block goog-flat-menu-button-caption"])[3]
[info] [phantom] Step anonymous 35/39: done in 18979ms.

I ve tried to set a bigger viewport like viewportSize : { width: 1280, height: 5000 }, but no help

I am using casperjs 1.1.0-beta3 and phantomjs 1.9.8 on Mac OS.

I ve also tried on a Ubuntu 14.04 with phantomjs 2.0 but still not working....

**Comment by jra11** [comment]
Should be corrected, feel free to test it
